title: Free HTML5/CSS3 Template by Peter Finla  # Name of the site
author:
  name: Peter Finla
metadata:
    description: 'An exclusive HTML5/CSS3 freebie by Peter Finlan, for Codrops.'

# Header customization
header:
  title: I'm Jonathan Doe.
  description: I'm a Manila based <span>graphic designer</span>, <span>illustrator</span> and <span>webdesigner</span> creating awesome and effective visual identities for companies of all sizes around the globe. Let's <a class="smoothscroll" href="#about">start scrolling</a> and learn more <a class="smoothscroll" href="#about">about me</a>.
  buttons:
    - text: "Back to the article"
      link: "http://tympanus.net/codrops/?p=19439"
      class: "learn-more-btn"

footer:
  links:
    - text: Terms &amp; Conditions
      url: "#"
    - text: Legals
      url: "#"
